# Why python for data analysis, machine learning?
There are lots of reasons that we want to use python for doing data science. It is certainly one of the younger programming languages used in the data science ecosystem (compared to say R and SAS) but it is used just as frequently for analysis as SAS and R. Having a good foundation in python and R, (and SAS or SPSS) should be a *must* for **every data scientist** and machine learning enthusiast. 

Here is a latex equation $\lambda=5$ 

In this course, python allows for an open source method of performing machine learning that runs from just about any machine. So let's start with looking at Numpy and Pandas pachages for analyzing data. 

With that in mind, let's go over the following:
- Numpy matrices
- Simple operations on arrays and matrices
- Indexing with numpy
- Pandas for tabular data
- Representing categorical data (discussion point)

In [1]:
import sys
import numpy as np

print(sys.version)
print(np.__version__)

3.12.13 | packaged by Anaconda, Inc. | (main, Jul  9 2026, 14:29:01) [Clang 20.1.8 ]
1.26.4

In [2]:
x = np.random.rand(5,3)
x

array([[0.60112884, 0.79706117, 0.94211349],
       [0.52796364, 0.49373164, 0.03395912],
       [0.01100947, 0.56918177, 0.96550018],
       [0.9011955 , 0.4408075 , 0.76309521],
       [0.70729123, 0.41499217, 0.11005385]])

In [3]:
x.shape

(5, 3)

In [4]:
x.dtype

dtype('float64')

In [5]:
# will this work?
y = np.random.rand(3,4)
z = x*y
z

ValueError: operands could not be broadcast together with shapes (5,3) (3,4)

In [6]:
# we can designate what matrix multiplication is directly using objects
z = np.dot(x,y)
z

array([[1.72316748, 1.20709513, 1.15163625, 1.45421421],
       [0.66344158, 0.76454864, 0.80790087, 0.81617207],
       [1.24744029, 0.60213878, 0.43969935, 0.76233546],
       [1.50755667, 1.13688575, 1.22675698, 1.4518263 ],
       [0.78694074, 0.8545209 , 0.94903819, 0.97303718]])

In [7]:
# or we can use the overloaded matrix multiplication operator
z = x @ y
z

array([[1.72316748, 1.20709513, 1.15163625, 1.45421421],
       [0.66344158, 0.76454864, 0.80790087, 0.81617207],
       [1.24744029, 0.60213878, 0.43969935, 0.76233546],
       [1.50755667, 1.13688575, 1.22675698, 1.4518263 ],
       [0.78694074, 0.8545209 , 0.94903819, 0.97303718]])

# Indexing

In [8]:
x1 = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
x1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
for row in range(x1.shape[0]):
    print(x1[row,1])

2
5
8

In [10]:
print(x1[:,1])
print(x1[:,1]>3)
# slicing
print(x1[ x1[:,1]>3 ])

[2 5 8]
[False  True  True]
[[4 5 6]
 [7 8 9]]

In [11]:
x2 = np.array(range(10))
print(x2)
x2.shape

[0 1 2 3 4 5 6 7 8 9]

(10,)

In [12]:
x_tmp = x2[:,np.newaxis]
x_tmp

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [13]:
idx = x2>5
print(idx)
print(x2[idx])

[False False False False False False  True  True  True  True]
[6 7 8 9]

In [14]:
x2[x2>5] # rows of x2 where x2 is greater than 5

array([6, 7, 8, 9])

# Named columns
So what if we have a matrix of data where each row is some observation of features and the feature values are represented in each column?

In [15]:
col_names = ['temperature','time','day']
data = np.array([[64,2100,1],
                 [50,2200,4],
                 [48,2300,3],
                 [34,0,   2],
                 [30,100, 5]])
data

array([[  64, 2100,    1],
       [  50, 2200,    4],
       [  48, 2300,    3],
       [  34,    0,    2],
       [  30,  100,    5]])

In [16]:
data2 = data[data[:,1]>1500]
data2

array([[  64, 2100,    1],
       [  50, 2200,    4],
       [  48, 2300,    3]])

In [17]:
# pandas to the rescue
import pandas as pd
print(pd.__version__)

df = pd.DataFrame(data,columns=col_names)
df

3.0.5

   temperature  time  day
0           64  2100    1
1           50  2200    4
2           48  2300    3
3           34     0    2
4           30   100    5

In [18]:
# can always access the backend numpy with .values
print(type(df.to_numpy()))
df.to_numpy()

<class 'numpy.ndarray'>

array([[  64, 2100,    1],
       [  50, 2200,    4],
       [  48, 2300,    3],
       [  34,    0,    2],
       [  30,  100,    5]])

In [19]:
df[df.time>1500]

   temperature  time  day
0           64  2100    1
1           50  2200    4
2           48  2300    3

In [20]:
# lets get a description of the data
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   temperature  5 non-null      int64
 1   time         5 non-null      int64
 2   day          5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [21]:
df.loc[df.day==1,'day'] = 'Mon'
df

TypeError: Invalid value 'Mon' for dtype 'int64'

In [22]:
# there is almost always a more efficient built in pandas function
df.day = df.day.replace(to_replace=range(7),
               value=['Su','Mon','Tues','Wed','Th','Fri','Sat'])
df

   temperature  time   day
0           64  2100   Mon
1           50  2200    Th
2           48  2300   Wed
3           34     0  Tues
4           30   100   Fri

In [23]:
# notice how the type of the column has changed to an object "categorical"
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   temperature  5 non-null      int64
 1   time         5 non-null      int64
 2   day          5 non-null      object
dtypes: int64(2), object(1)
memory usage: 252.0+ bytes

In [24]:
# one hot encoding example
pd.get_dummies(df.day)

     Fri    Mon     Th   Tues    Wed
0  False   True  False  False  False
1  False  False   True  False  False
2  False  False  False  False   True
3  False  False  False   True  False
4   True  False  False  False  False

# Some Pandas Syntax

In [25]:
# slicing into a pandas dataframe
print(df.day)
print(df['day'])
df[['day','temperature']]

0     Mon
1      Th
2     Wed
3    Tues
4     Fri
Name: day, dtype: object
0     Mon
1      Th
2     Wed
3    Tues
4     Fri
Name: day, dtype: object

    day  temperature
0   Mon           64
1    Th           50
2   Wed           48
3  Tues           34
4   Fri           30

In [26]:
print(df.day[2]) # print the value
print(df.day[2:]) # print as pandas series

Wed
2     Wed
3    Tues
4     Fri
Name: day, dtype: object

In [27]:
# index location
df.iloc[3:]

   temperature  time   day
3           34     0  Tues
4           30   100   Fri

In [28]:
df.iloc[3:][['day','temperature']]

    day  temperature
3  Tues           34
4   Fri           30

In [29]:
df[['day','temperature']].iloc[3:]

    day  temperature
3  Tues           34
4   Fri           30

In [30]:
df.mean(numeric_only=True)

temperature      45.2
time           1340.0
dtype: float64

In [31]:
df.std(numeric_only=True)

temperature      13.608821
time           1180.254210
dtype: float64

In [32]:
df.mean(numeric_only=True)/df.std(numeric_only=True)

temperature    3.321375
time           1.135349
dtype: float64

In [33]:
tmp = df.time.unique()
tmp

array([2100, 2200, 2300,    0,  100])

# Pandas Block Manager
Let's take a look at some important points from the following post:
 - https://uwekorn.com/2020/05/24/the-one-pandas-internal.html

This is the pandas BlockManager, which tries to group internal structures together to make things fast:
<img src="https://uwekorn.com/images/pd-df-perception.002.png" width=200 height=200 />

In [34]:
df

   temperature  time   day
0           64  2100   Mon
1           50  2200    Th
2           48  2300   Wed
3           34     0  Tues
4           30   100   Fri

In [35]:
print(df._mgr.nblocks)
df._mgr

2

BlockManager
Items: Index(['temperature', 'time', 'day'], dtype='str')
Axis 1: RangeIndex(start=0, stop=5, step=1)
NumpyBlock: slice(0, 2, 1), 2 x 5, dtype: int64
NumpyBlock: slice(2, 3, 1), 1 x 5, dtype: object

## Advantages and disadvantages:
This can speed up operations because it inhenertly can apply operations along columns in a single pass over the data (like sums, etc.) and therefore is using c++ for much of the heavy lifting.

But, **it might be bad** when you are adding columns to the data because it can trigger consolidation of columns, which means copying over data in numpy to creata new matrix. The slow down also doesn't show up until a needed column is accessed (lazy data copying). Let's do an example from:  https://uwekorn.com/2020/05/24/the-one-pandas-internal.html

**Block consolidation is triggered after 100 blocks of data are reached.**

In [36]:
# we will start with a 2 column dataframe
# one column is an int and the other a float
# becasue there are two datatypes this has two blocks
df_example = pd.DataFrame({
    'int64': np.arange(1024 * 1024, dtype=np.int64),
    'float64': np.arange(1024 * 1024, dtype=np.float64),
})
df_example

           int64    float64
0              0        0.0
1              1        1.0
2              2        2.0
3              3        3.0
4              4        4.0
...          ...        ...
1048571  1048571  1048571.0
1048572  1048572  1048572.0
1048573  1048573  1048573.0
1048574  1048574  1048574.0
1048575  1048575  1048575.0

[1048576 rows x 2 columns]

In [37]:
%%time 

# but now lets start to add columns one by one
# to be fast, pandas adds each as a new block 
for i in range(10):
    df_example[f'new_{i}'] = df_example['int64'].to_numpy()
    
print(df_example._mgr.nblocks)
df_example

12
CPU times: user 9.76 ms, sys: 9.84 ms, total: 19.6 ms
Wall time: 16.8 ms

,int64,float64,new_0,new_1,new_2,new_3,new_4,new_5,new_6,new_7,new_8,new_9
0,0,0.0,0,0,0,0,0,0,0,0,0,0
1,1,1.0,1,1,1,1,1,1,1,1,1,1
2,2,2.0,2,2,2,2,2,2,2,2,2,2
3,3,3.0,3,3,3,3,3,3,3,3,3,3
4,4,4.0,4,4,4,4,4,4,4,4,4,4
...,...,...,...,...,...,...,...,...,...,...,...,...
1048571,1048571,1048571.0,1048571,1048571,1048571,1048571,1048571,1048571,1048571,1048571,1048571,1048571
1048572,1048572,1048572.0,1048572,1048572,1048572,1048572,1048572,1048572,1048572,1048572,1048572,1048572
1048573,1048573,1048573.0,1048573,1048573,1048573,1048573,1048573,1048573,1048573,1048573,1048573,1048573
1048574,1048574,1048574.0,1048574,1048574,1048574,1048574,1048574,1048574,1048574,1048574,1048574,1048574
1048575,1048575,1048575.0,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575,1048575

In [38]:
%time df_example['dummy_name5'] = df_example['int64'].to_numpy() # copy over some new columns
print('Number of blocks in data:',df_example._mgr.nblocks)

# force consolidation by writing a new df and overwriting
%time df_example = pd.DataFrame({col: df_example[col] for col in df_example.columns})
print('Number of blocks in data:',df_example._mgr.nblocks)

CPU times: user 2.23 ms, sys: 3.05 ms, total: 5.28 ms
Wall time: 3.04 ms
Number of blocks in data: 13
CPU times: user 15.7 ms, sys: 22.4 ms, total: 38.1 ms
Wall time: 38 ms
Number of blocks in data: 2

In [39]:
df_example.info()

<class 'pandas.DataFrame'>
RangeIndex: 1048576 entries, 0 to 1048575
Data columns (total 13 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   int64        1048576 non-null  int64
 1   float64      1048576 non-null  float64
 2   new_0        1048576 non-null  int64
 3   new_1        1048576 non-null  int64
 4   new_2        1048576 non-null  int64
 5   new_3        1048576 non-null  int64
 6   new_4        1048576 non-null  int64
 7   new_5        1048576 non-null  int64
 8   new_6        1048576 non-null  int64
 9   new_7        1048576 non-null  int64
 10  new_8        1048576 non-null  int64
 11  new_9        1048576 non-null  int64
 12  dummy_name5  1048576 non-null  int64
dtypes: float64(1), int64(12)
memory usage: 104.0 MB